# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SFlashMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SFlashMap
  
   pod 'AFNetworking', '~> 3.0'
   pod 'JSONModel'
   pod 'Alamofire', '~> 4.0.0'
   pod 'SwiftyJSON'
   pod 'JGProgressHUD'

  target 'SFlashMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SFlashMapUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
